homeassistant:
  name: 旌启智家
  latitude: 30.23927
  longitude: 120.05633
  elevation: 32
  unit_system: metric
  currency: CNY
  time_zone: Asia/Shanghai
  external_url: !secret external_url
  internal_url: !secret external_url
  customize: !include customize.yaml

http:
  server_port: 88
  ssl_key: ~/.homeassistant/extras/setup/ssl.key
  ssl_certificate: ~/.homeassistant/extras/setup/ssl.crt

# default_config:

automation: !include_dir_merge_list automations
# scene: !include scenes.yaml
# script: !include scripts.yaml

# usb:
# bluetooth:

# backup
# cloud:
config:
# energy:
frontend:
mobile_app:
system_health:
# homeassistant_alerts:
webhook:
# updater:

# dhcp:
# ssdp:
# zeroconf:

input_boolean:
input_button:
input_datetime:
input_number:
input_select:
input_text:
counter:
timer:

#my:
tag:
sun:
zone:
image:
# stream:
# media_source:

# map:
logbook:
history:
  exclude:
    domains:
      - sun
      - group
      - script
      - climate
      - automation
      - input_text
      - input_select
      - input_boolean

logger:
  default: warning
  logs:
    custom_components: debug
    custom_components.zhimi: debug
    custom_components.zhimijia: debug

recorder:
  purge_keep_days: 2

# tts:
#   - platform: baidu
#     app_id: !secret baidu_app_id
#     api_key: !secret baidu_api_key
#     secret_key: !secret baidu_secret_key

homekit: !include homekit.yaml

modbus:
  type: rtuovertcp
  host: KongTiaoWangGuan
  port: 8899

device_tracker:
  - platform: ping
    scan_interval: 120
    hosts:
      zhuwodianshi: 192.168.1.6
      ketingdianshi: 192.168.1.7
      touyingyi: 192.168.1.9
      babashouji: 192.168.1.21
      mamashouji: 192.168.1.22
      nainaishouji: 192.168.1.23
      # yeyeshouji: 192.168.1.24
      dabaoshouji: 192.168.1.25
      ayishouji: 192.168.1.26
      dabaopingban: 192.168.1.28
      xiaozhipingban: 192.168.1.29

person:
  - name: 爸爸
    id: baba
    device_trackers: device_tracker.babashouji
  - name: 妈妈
    id: mama
    device_trackers: device_tracker.mamashouji
  # - name: 爷爷
  #   id: yeye
  #   device_trackers: device_tracker.yeyeshouji
  - name: 奶奶
    id: nainai
    device_trackers: device_tracker.nainaishouji
  - name: 大宝
    id: dabao
    device_trackers: [device_tracker.dabaoshouji, device_tracker.dabaopingban]
  - name: 小智
    id: xiaozhi
    device_trackers: device_tracker.xiaozhipingban
  - name: 阿姨
    id: ayi
    device_trackers: device_tracker.ayishouji

weather:
  - platform: zhicaiyun
    name: 天气

#sensor: !include sensors.yaml
switch: !include switches.yaml
light: !include lights.yaml
fan: !include fans.yaml
mqtt: !include mqtt.yaml

climate:
  # - platform: zhisaswell
  #   username: !secret saswell_username
  #   password: !secret saswell_password
  - platform: zhimodbus
    name: [餐厅空调, 客厅空调, 主卧空调, 儿童房空调]
    fan_mode: { registers: [6, 10, 14, 18] }
    fan_modes: { 自动: 0, 一档: 1, 二档: 2, 三档: 3, 四档: 4, 五档: 5 }
    hvac_mode: { registers: [5, 9, 13, 17] }
    hvac_modes: { 'off': 0, cool: 1, heat: 2, dry: 3, fan_only: 4 }
    hvac_off: { registers: [1, 2, 3, 4], register_type: coil }
    target_temperature: { registers: [4, 8, 12, 16] }
    temperature: { registers: [3, 6, 9, 12], register_type: input, scale: 0.1 }
  - platform: zhiremote
    name: 书房空调
    sender: remote.shu_fang_yao_kong
    command: mitsubishi_climate
    sensor: sensor.shu_fang_wen_du

cover:
  - platform: zhimijia
    name: 书房晾衣架
    did: 57379167
  - platform: zhiremote
    name: 书房窗帘
    sender: remote.shu_fang_yao_kong
    travel: 13
    command: dooya_cover
  - platform: zhiremote
    name: 书房幕布
    icon: mdi:projector-screen
    sender: remote.shu_fang_yao_kong
    travel: 45
    command: elite_screen

media_player:
  - platform: zhiremote
    name: 书房投影仪
    icon: mdi:projector
    sender: remote.shu_fang_yao_kong
    command: viewsonic_projector
    sensor: device_tracker.projector
  # - platform: dlna_dmr
  #   name: 天猫精灵
  #   url: http://Magic:49153/description.xml

# camera:
#   - platform: ffmpeg
#     name: 书房摄像机
#     input: !secret rtsp_camera6
#   - platform: generic
#     name: 餐厅摄像机
#     still_image_url: http://Camera1/last.cgi
#     #stream_source: rtsp://Camera1/live/ch00_0
#   - platform: ffmpeg
#     name: 过道摄像机
#     input: rtsp://Camera2/ch0_1.h264
#  - platform: generic
#    name: 主卧摄像机
#    still_image_url: http://Camera5/last.cgi
#    #stream_source: rtsp://Camera5/live/ch00_0

vacuum:
  - platform: zhimijia
    model: viomi.washer.v13
    name: 浴室洗衣机
    did: 410056542
#   - platform: xiaomi_miio
#     name: 扫地机
#     host: SaoDiJi
#     token: !secret vacuum_token

zhiact:

zhimi:
  username: !secret zhimi_username
  password: !secret zhimi_password

zhimsg:
  - platform: ding
    name: 钉钉信使
    token: !secret dingbot_token
    secret: !secret dingbot_secret
  - platform: miai
    name: 客厅音箱
    did: 380205692
    model: x08c
  - platform: miai
    name: 次卧音箱
    did: 89463074
    model: lx01
  - platform: miai
    name: 儿童房音箱
    did: 267090026
    model: lx04

zhibot:
  # - platform: genie
  #   token: !secret zhibot_token
  - platform: genie2
    file: !secret genie2bot_file
    text: !secret genie2bot_text
    token: !secret zhibot_token
  - platform: miai
    token: !secret zhibot_token
  - platform: ding
    token: !secret zhibot_token
  - platform: ding
    name: 过道音箱
    token: !secret zhibot_token
  - platform: ding
    name: 客厅音箱
    token: !secret zhibot_token
  - platform: ding
    name: 儿童房音箱
    token: !secret zhibot_token

zhiaqara:
  name: 小米网关
  key: 3ECB50168D7F4AEB

zhibroad:
  - name: 书房遥控
    host: ShuFangYaoKong
  - name: 客厅遥控
    host: KeTingYaoKong
  # - name: 客厅插座
  #   host: KeTingChaZuo

zhibravia:
  - name: 主卧电视
    host: ZhuWoDianShi
  - name: 客厅电视
    host: KeTingDianShi

zhilace:

lovelace:
  mode: storage
  dashboards:
    zhilace-zone:
      mode: yaml
      title: 分区
      icon: mdi:home-floor-a
      show_in_sidebar: true
      filename: zhilace-zone.yaml
    zhilace-type:
      mode: yaml
      title: 分类
      icon: mdi:home-floor-b
      show_in_sidebar: true
      filename: zhilace-type.yaml

panel_iframe:
  dash:
    title: 面板
    icon: mdi:microsoft
    url: /local/dash.html

shell_command:
  station_off: 'ssh root@Station shutdown -h now'
  magic_on: "adb connect magic && adb -s magic shell 'input keyevent 82; am start -n com.thanksmister.iot.wallpanel/.ui.activities.WelcomeActivity'"
  magic_off: "adb connect magic && adb -s magic shell 'input keyevent 82; input keyevent 26'"
  x9300d_off: 'adb connect x9300d && adb -s x9300d shell reboot -p'
  x9400d_off: 'adb connect x9400e && adb -s x9400e shell reboot -p'
