homeassistant:
  name: 旌启智家
  latitude: 30.23927
  longitude: 120.05633
  elevation: 32
  unit_system: metric
  currency: CNY
  country: CN
  time_zone: Asia/Shanghai
  external_url: !secret external_url
  internal_url: !secret external_url
  customize: !include customize.yaml

http:
  server_port: 88
  ssl_key: /root/.homeassistant/ssl.key
  ssl_certificate: /root/.homeassistant/ssl.crt

# default_config:

# usb:
# bluetooth:

# backup
# cloud:
config:
# energy:
frontend:
# mobile_app:
system_health:
# homeassistant_alerts:
# webhook:
# updater:

# dhcp:
# ssdp:
# zeroconf:

# input_boolean:
# input_button:
# input_datetime:
# input_number:
# input_select:
input_text:
# counter:
# timer:

#my:
# tag:
sun:
zone:
# stream:
# media_source:

# map:
logbook:
history:
logger:
  default: warning
  logs:
    custom_components: debug

recorder:
  purge_keep_days: 4
  exclude:
    domains:
      - sun
      - group
      - script
      - climate
      - automation
      - input_text
      - input_select
      - input_boolean

# modbus:
#   - type: rtuovertcp
#     host: 192.168.1.60
#     port: 8899
#     switches:
#       - name: 餐厅空调
#         address: 1
#         command_on: 1
#         command_off: 0
#         write_type: coil
#       - name: 客厅空调
#         address: 2
#         command_on: 1
#         command_off: 0
#         write_type: coil
#       - name: 主卧空调
#         address: 3
#         command_on: 1
#         command_off: 0
#         write_type: coil
#       - name: 儿童房空调
#         address: 4
#         command_on: 1
#         command_off: 0
#         write_type: coil

zhimi:
  username: !secret zhimi_username
  password: !secret zhimi_password

device_tracker:
  - platform: ping
    scan_interval: 120
    hosts:
      touyingyi: 192.168.1.5
      ketingdianshi: 192.168.1.8
      zhuwodianshi: 192.168.1.9
      babashouji: 192.168.1.20
      mamashouji: 192.168.1.21
      dabaopingban: 192.168.1.24
      xiaozhipingban: 192.168.1.25
      ayishouji: 192.168.1.29

person:
  - name: 爸爸
    id: baba
    device_trackers: device_tracker.babashouji
  - name: 妈妈
    id: mama
    device_trackers: device_tracker.mamashouji
  - name: 大宝
    id: dabao
    device_trackers: device_tracker.dabaopingban
  - name: 小智
    id: xiaozhi
    device_trackers: device_tracker.xiaozhipingban
  - name: 阿姨
    id: ayi
    device_trackers: device_tracker.ayishouji

weather:
  - platform: zhicaiyun
    name: 天气

climate:
  - platform: zhisaswell
    name: 客厅地暖
    host: 192.168.1.56
    device: 10382435CC059E60
  - platform: zhisaswell
    name: 主卧地暖
    host: 192.168.1.57
    device: 10382435CC059F72
  # - platform: zhimodbus
  #   name: [餐厅空调, 客厅空调, 主卧空调, 儿童房空调]
  #   fan_mode: { registers: [6, 10, 14, 18] }
  #   fan_modes: { 自动: 0, 一档: 1, 二档: 2, 三档: 3, 四档: 4, 五档: 5 }
  #   hvac_mode: { registers: [5, 9, 13, 17] }
  #   hvac_modes: { 'off': 0, cool: 1, heat: 2, dry: 3, fan_only: 4 }
  #   hvac_off: { registers: [1, 2, 3, 4], register_type: coil }
  #   target_temperature: { registers: [4, 8, 12, 16] }
  #   temperature: { registers: [3, 6, 9, 12], register_type: input, scale: 0.1 }
  # - platform: zhiremote
  #   name: 书房空调
  #   sender: remote.shu_fang_yao_kong
  #   command: mitsubishi_climate
  #   sensor: sensor.shu_fang_wen_du

cover:
  - platform: zhimijia
    name: 书房晾衣机
    did: 57379167
  - platform: zhiremote
    name: 书房窗帘
    sender: remote.shu_fang_yao_kong
    travel: 13
    command: dooya_cover
  - platform: zhiremote
    name: 书房幕布
    icon: mdi:projector-screen
    sender: remote.shu_fang_yao_kong
    travel: 45
    command: elite_screen

media_player:
  - platform: zhiremote
    name: 书房投影仪
    icon: mdi:projector
    sender: remote.shu_fang_yao_kong
    command: viewsonic_projector
    sensor: device_tracker.touyingyi

vacuum:
  - platform: zhimijia
    model: viomi.washer.v13
    name: 阳台洗衣机
    did: 410056542
  - platform: zhimijia
    model: viomi.washer.v33
    name: 浴室洗衣机
    did: 619765138
#   - platform: xiaomi_miio
#     name: 扫地机
#     host: SaoDiJi
#     token: !secret vacuum_token

zhiact:

zhimsg:
  - platform: ding
    name: 钉钉信使
    token: !secret dingbot_token
    secret: !secret dingbot_secret
  - platform: miai
    name: 客厅音箱
    did: 380205692
    model: x08c
  - platform: miai
    name: 次卧音箱
    did: 89463074
    model: lx01
  - platform: miai
    name: 儿童房音箱
    did: 267090026
    model: lx04

zhibot:
  - platform: genie2
    file: !secret genie2bot_file
    text: !secret genie2bot_text
    token: !secret zhibot_token
  - platform: miai
    token: !secret zhibot_token
  - platform: ding
    token: !secret zhibot_token
  - platform: ding
    name: 过道音箱
    token: !secret zhibot_token
  - platform: ding
    name: 客厅音箱
    token: !secret zhibot_token
  - platform: ding
    name: 儿童房音箱
    token: !secret zhibot_token

zhiaqara:
  name: 小米网关
  key: 3ECB50168D7F4AEB
  interface: 192.168.1.2

zhibroad:
#   - name: 客厅遥控
#     host: 192.168.1.54
  - name: 书房遥控
    host: 192.168.1.53
  - name: 客厅插座
    host: 192.168.1.55

zhibravia:
  - name: 客厅电视
    host: 192.168.1.8
    mac: 04:5D:4B:3F:8D:93
  - name: 主卧电视
    host: 192.168.1.9
    mac: 10:4F:A8:EF:7F:86

zhilace:

lovelace:
  mode: storage
  dashboards:
    zhilace-zone:
      mode: yaml
      title: 分区
      icon: mdi:home-floor-a
      show_in_sidebar: true
      filename: zhilace-zone.yaml
    zhilace-type:
      mode: yaml
      title: 分类
      icon: mdi:home-floor-b
      show_in_sidebar: true
      filename: zhilace-type.yaml
    zhilace-dash:
      mode: yaml
      title: 面板
      icon: mdi:microsoft
      show_in_sidebar: true
      filename: zhilace-dash.yaml

# shell_command:
  #server_off: 'ssh root@192.168.1.2 shutdown -h now'
  # magic_on: "adb connect 192.168.1.15 && adb -s 192.168.1.15 shell 'input keyevent 82; am start -n com.thanksmister.iot.wallpanel/.ui.activities.WelcomeActivity'"
  # magic_off: "adb connect 192.168.1.15 && adb -s 192.168.1.15 shell 'input keyevent 82; input keyevent 26'"
  # x9300d_off: 'adb connect 192.168.1.9 && adb -s 192.168.1.9 shell reboot -p'
  # x9400d_off: 'adb connect 192.168.1.8 && adb -s 192.168.1.8 shell reboot -p'

command_line:
  - switch:
      name: 聚合网盘
      icon: mdi:google-drive
      command_on: 'ssh -p 222 192.168.1.2 "docker start xiaoya"'
      command_off: 'ssh -p 222 192.168.1.2 "docker stop xiaoya"'
      command_state: 'ssh -p 222 192.168.1.2 "docker inspect -f {{json\ .State.Running}} xiaoya"'
      value_template: '{{ value == "true" }}'
      scan_interval: 600

fan: !include fans.yaml
mqtt: !include mqtt.yaml
light: !include lights.yaml
#sensor: !include sensors.yaml
#switch: !include switches.yaml

# scene: !include scenes.yaml
# script: !include scripts.yaml
homekit: !include homekit.yaml
automation: !include_dir_merge_list automations
