- platform: zhimijia
  model: zhimi.fan.v3
  name: 儿童房风扇
  did: 63038010
- platform: zhimijia
  model: zhimi.fan.fa1
  name: 书房风扇
  did: 242978949
- platform: zhimijia
  model: zhimi.fan.za3
  name: 长辈房风扇
  did: 106565511
- platform: zhimijia
  model: zhimi.airfresh.va2
  name: 客厅新风机
  did: 80578920
- platform: zhimijia
  model: zhimi.airfresh.va2
  name: 主卧新风机
  did: 99281481
- platform: zhimijia
  model: zhimi.airpurifier.m1
  name: 次卧净化器
  did: 61061613
- platform: zhiremote
  name: 客厅风扇
  sender: remote.ke_ting_yao_kong
  command: midea_fan
