- platform: wake_on_lan
  name: 网络存储
  mac: 00:11:32:6B:75:F7
  host: Station
  turn_off:
    service: shell_command.station_off
- platform: mqtt
  name: 餐厅筒灯
  state_topic: Sonoff1/relay/1
  command_topic: Sonoff1/relay/1/set
  availability_topic: Sonoff1/status
- platform: mqtt
  name: 客厅筒灯
  state_topic: Sonoff1/relay/2
  command_topic: Sonoff1/relay/2/set
  availability_topic: Sonoff1/status
- platform: mqtt
  name: 洗手间排气扇
  state_topic: Hassmart2/relay/1
  command_topic: Hassmart2/relay/1/set
  availability_topic: Hassmart2/status
- platform: mqtt
  name: 浴室排气扇
  state_topic: Hassmart3/relay/0
  command_topic: Hassmart3/relay/0/set
  availability_topic: Hassmart3/status
- platform: zhimqtt
  name: 书房音箱
  state_topic: NodeMCU2/relay/0
  command_topic: NodeMCU2/relay/0/set
  availability_topic: NodeMCU2/status
  value_template: '{% if value == "关闭" %}OFF{% else %}ON{% endif %}'
  icon_template: '{% if value == "关闭" %}mdi:speaker-off{% elif value == "蓝牙" %}mdi:speaker-bluetooth{% elif value == "光纤" %}mdi:speaker-wireless{% elif value == "优盘" %}mdi:usb{% elif value == "辅助" %}mdi:video-input-component{% else %}mdi:speaker{% endif %}'
# - platform: template
#   switches:
#     zhu_wo_dian_shi:
#       friendly_name: 主卧电视电源
#       value_template: '{{ is_state("device_tracker.x9300d", "home") }}'
#       turn_on:
#         service: mqtt.publish
#         data:
#           topic: NodeMCU5/irout/set
#           payload: '2416,592,1210,594,608,618,1186,616,586,592,1210,618,584,618,586,616,1186,618,584,618,584,616,586,592,608,1,2,38'
#       turn_off:
#         service: shell_command.x9300d_off
