- alias: 阳台按钮单击—预约洗衣
  trigger:
    - platform: event
      event_type: xiaomi_aqara.click
      event_data:
        entity_id: binary_sensor.switch_158d0001e59b33
        click_type: single
  action:
    - service: vacuum.send_command
      data:
        entity_id: vacuum.yang_tai_xi_yi_ji
        command: turn_on;Mode=0;appoint

- alias: 阳台按钮长按—预约洗烘
  trigger:
    - platform: event
      event_type: xiaomi_aqara.click
      event_data:
        entity_id: binary_sensor.switch_158d0001e59b33
        click_type: long_click_press
  action:
    - service: vacuum.send_command
      data:
        entity_id: vacuum.yang_tai_xi_yi_ji
        command: turn_on;Mode=2;appoint

- alias: 阳台按钮双击—取消预约
  trigger:
    - platform: event
      event_type: xiaomi_aqara.click
      event_data:
        entity_id: binary_sensor.switch_158d0001e59b33
        click_type: double
  action:
    - service: vacuum.stop
      entity_id: vacuum.yang_tai_xi_yi_ji

- alias: 浴室按钮单击—预约洗衣
  trigger:
    - platform: event
      event_type: xiaomi_aqara.click
      event_data:
        entity_id: binary_sensor.switch_158d000201a73f
        click_type: single
  action:
    - service: vacuum.send_command
      data:
        entity_id: vacuum.yu_shi_xi_yi_ji
        command: turn_on;Mode=0;sleep;sleep;appoint

- alias: 浴室按钮长按—预约洗烘
  trigger:
    - platform: event
      event_type: xiaomi_aqara.click
      event_data:
        entity_id: binary_sensor.switch_158d000201a73f
        click_type: long_click_press
  action:
    - service: vacuum.send_command
      data:
        entity_id: vacuum.yu_shi_xi_yi_ji
        command: turn_on;Mode=2;sleep;sleep;appoint

- alias: 浴室按钮双击—取消预约
  trigger:
    - platform: event
      event_type: xiaomi_aqara.click
      event_data:
        entity_id: binary_sensor.switch_158d000201a73f
        click_type: double
  action:
    - service: vacuum.stop
      entity_id: vacuum.yu_shi_xi_yi_ji
