- alias: 调节客厅新风机
  trigger:
    - platform: state
      entity_id: sensor.ke_ting_er_yang_hua_tan
  action:
    - service: zhiact.actuate
      data:
        sensor_id: sensor.ke_ting_er_yang_hua_tan
        sensor_values: [490, 540, 650, 720]
        entity_id: fan.ke_ting_xin_feng_ji
        entity_attr: speed
        entity_values: [Auto, Low, Middle, Strong]
        condition_attr: mode
        condition_values: [auto, low, middle, strong]

- alias: 调节主卧新风机
  trigger:
    - platform: state
      entity_id: sensor.zhu_wo_er_yang_hua_tan
  action:
    - service: zhiact.actuate
      data:
        sensor_id: sensor.zhu_wo_er_yang_hua_tan
        sensor_values: [500, 600, 700, 800]
        alt_sensor_values: [500, 700, 900, 1300]
        entity_id: fan.zhu_wo_xin_feng_ji
        entity_attr: speed
        entity_values: [Auto, Low, Middle, Strong]
        condition_attr: mode
        condition_values: [auto, low, middle, strong]
