- alias: 入户门欢迎
  trigger:
    - platform: state
      entity_id: binary_sensor.door_window_sensor_158d0001f3e5be
      from: 'on'
      to: 'off'
  action:
    - service: xiaomi_aqara.play_ringtone
      data:
        gw_mac: 34CE0090901A
        ringtone_id: 10001
        ringtone_vol: 80

- alias: 入户门提醒
  trigger:
    - platform: state
      entity_id: binary_sensor.door_window_sensor_158d0001f3e5be
      from: 'off'
      to: 'on'
      for:
        minutes: 2
  action:
    - service: zhimsg.ding
      data:
        message: 入户门长时间开启，请检查
    - service: xiaomi_aqara.play_ringtone
      data:
        gw_mac: 34CE0090901A
        ringtone_id: 10013
        ringtone_vol: 100
    - delay: 120
    - condition: state
      entity_id: binary_sensor.door_window_sensor_158d0001f3e5be
      state: 'on'
    - service: automation.trigger
      entity_id: automation.ru_hu_men_ti_xing

# - alias: 阳台门感应
#   trigger:
#     - platform: state
#       entity_id: binary_sensor.door_window_sensor_158d000228a52b
#       from: 'off'
#       to: 'on'
#     - platform: state
#       entity_id: binary_sensor.door_window_sensor_158d000228a52b
#       from: 'on'
#       to: 'off'
#   condition:
#     - condition: state
#       entity_id: sun.sun
#       state: below_horizon
#   action:
#     - service_template: '{% if trigger.to_state.state == "on" %}light.turn_on{% else %}light.turn_off{% endif %}'
#       entity_id: light.balcony_light

- alias: 阳台门提醒
  trigger:
    - platform: numeric_state
      entity_id: sensor.yang_tai_ke_li_wu
      above: 60
      for:
        minutes: 5
    - platform: state
      entity_id: binary_sensor.door_window_sensor_158d000228a52b
      from: 'off'
      to: 'on'
      for:
        seconds: 60
    - platform: time
      at: '21:00:00'
  condition:
    - condition: state
      entity_id: binary_sensor.door_window_sensor_158d000228a52b
      state: 'on'
    - condition: time
      after: '06:00'
      before: '23:00'
  action:
    - service: zhimsg.miai
      data_template:
        message: '{% if now().hour >= 21 %}晚上请关好阳台门{% else %}阳台PM2.5为{% set PM25 = states("sensor.yang_tai_ke_li_wu") | int %}{{ PM25 }}，{% if PM25 < 20 %}空气很好{% elif PM25 < 40 %}空气不错{% elif PM25 < 60 %}空气一般{% elif PM25 < 80 %}空气不好，请关好阳台门{% else %}空气污染，请关好阳台门和其它门窗{% endif %}{% endif %}'
    - delay: 120
    - condition: state
      entity_id: binary_sensor.door_window_sensor_158d000228a52b
      state: 'on'
    - condition: or
      conditions:
        - condition: numeric_state
          entity_id: sensor.yang_tai_ke_li_wu
          above: 60
        - condition: time
          after: '21:00'
          before: '23:00'
    - service: automation.trigger
      entity_id: automation.yang_tai_men_ti_xing

- alias: 厨房门提醒
  trigger:
    - platform: state
      entity_id: binary_sensor.door_window_sensor_158d0001f3d2d1
      from: 'off'
      to: 'on'
      for:
        minutes: 2
    - platform: time
      at: '21:10:00'
  condition:
    - condition: state
      entity_id: binary_sensor.door_window_sensor_158d0001f3d2d1
      state: 'on'
    - condition: time
      after: '21:00'
      before: '23:00'
  action:
    - service: xiaomi_aqara.play_ringtone
      data:
        gw_mac: 34CE0090901A
        ringtone_id: 10015
        ringtone_vol: 60
    - delay: 120
    - condition: state
      entity_id: binary_sensor.door_window_sensor_158d0001f3d2d1
      state: 'on'
    - service: automation.trigger
      entity_id: automation.chu_fang_men_ti_xing
