#
- alias: 过道感应-开关背景灯
  trigger:
    - platform: state
      entity_id: binary_sensor.motion_sensor_158d0001d66ce9
      from: 'off'
      to: 'on'
  condition:
      - condition: numeric_state
        entity_id: sensor.can_ting_liang_du
        below: 550
  action:
    # - service: mqtt.publish
    #   data:
    #     topic: Dashboard/command
    #     payload: '{wake: true}'
    - service: light.turn_on
      entity_id: light.guo_dao_ju_deng
    - wait_template: '{{ is_state("binary_sensor.motion_sensor_158d0001d66ce9", "off") }}'
    - service: light.turn_off
      entity_id: light.guo_dao_ju_deng
