- alias: 餐厅空气质量变化-调控净化器
  mode: restart
  trigger:
    - platform: state
      entity_id: sensor.can_ting_kong_qi_zhi_liang
  action:
    - service: zhiact.actuate
      data:
        sensor_id: sensor.can_ting_kong_qi_zhi_liang
        sensor_values: [10, 20, 50]
        entity_id: fan.can_ting_jing_hua_qi
        entity_attr: preset_mode
        entity_values: [自动, 中档, 高档]
        # condition_attr: oscillating
        # condition_values: [false]

- alias: 次卧空气质量变化-调控净化器
  mode: restart
  trigger:
    - platform: state
      entity_id: sensor.ci_wo_kong_qi_zhi_liang
  action:
    - service: zhiact.actuate
      data:
        sensor_id: sensor.ci_wo_kong_qi_zhi_liang
        sensor_values: [15, 25, 35, 45, 50, 60, 70, 80, 90]
        alt_sensor_values: [15, 30, 40, 50, 60, 70, 80, 90, 100]
        entity_id: fan.ci_wo_jing_hua_qi
        entity_attr: favorite_level
        service_attr: percentage
        entity_values: [20, 30, 40, 50, 60, 70, 80, 90, 100]
        condition_attr: mode
        condition_values: [idle, auto, favorite]

- alias: 儿童房空气质量变化-调控净化器
  mode: restart
  trigger:
    - platform: state
      entity_id: sensor.er_tong_fang_kong_qi_zhi_liang
  action:
    - service: zhiact.actuate
      data:
        sensor_id: sensor.er_tong_fang_kong_qi_zhi_liang
        sensor_values: [10, 20, 50]
        alt_sensor_values: [12, 30, 50]
        entity_id: fan.er_tong_fang_jing_hua_qi
        entity_attr: preset_mode
        entity_values: [自动, 中档, 高档]
        # condition_attr: oscillating
        # condition_values: [false]
        #delay: 0
