- alias: 书房投影仪开启-准备配套
  trigger:
    - platform: state
      entity_id: device_tracker.projector
      from: not_home
      to: home
  condition:
    - condition: state
      entity_id: cover.shu_fang_mu_bu
      state: open
  action:
    - service: cover.close_cover
      entity_id: cover.shu_fang_chuang_lian
    #- delay: 10
    - service: cover.close_cover
      entity_id: cover.shu_fang_mu_bu
    #- service: cover.close_cover
    #  entity_id: cover.airer
    - service: homeassistant.turn_off
      entity_id:
        - light.shu_fang_liang_yi_deng
        - light.shu_fang_tai_deng
    # - condition: numeric_state
    #   entity_id: sensor.shu_fang_wen_du
    #   above: 28
    # - service: climate.turn_on
    #   entity_id: climate.shu_fang_kong_diao

- alias: 书房投影仪关闭-收尾配套
  trigger:
    - platform: state
      entity_id: device_tracker.projector
      from: home
      to: not_home
  condition:
    - condition: state
      entity_id: cover.shu_fang_mu_bu
      state: closed
  action:
    # - service_template: '{% if is_state("sun.sun", "below_horizon") %}light.turn_on{% else %}light.turn_off{% endif %}'
    #   entity_id: light.shu_fang_liang_yi_deng
    - service: cover.open_cover
      entity_id: cover.shu_fang_mu_bu
    #- delay: 10
    # - service: climate.turn_off
    #   entity_id: climate.shu_fang_kong_diao
    - condition: state
      entity_id: sun.sun
      state: above_horizon
    - service: cover.open_cover
      entity_id: cover.shu_fang_chuang_lian

# - alias: 书房按钮单击—开关卷帘
#   trigger:
#     - platform: event
#       event_type: xiaomi_aqara.click
#       event_data:
#         entity_id: binary_sensor.switch_158d000201a73f
#         click_type: single
#   action:
#     - service: zhimsg.ke_ting_yin_xiang
#       data:
#         message: 正在开关卷帘

# - alias: 书房按钮双击—开关播放器
#   trigger:
#     - platform: event
#       event_type: xiaomi_aqara.click
#       event_data:
#         entity_id: binary_sensor.switch_158d000201a73f
#         click_type: double
#   action:
#     - service_template: 'switch.turn_{% if is_state("media_player.shu_fang_tou_ying_yi", "on") %}off{% else %}on{% endif %}'
#       entity_id: switch.shu_fang_yin_xiang
#     - service: automation.trigger
#       entity_id: automation.shu_fang_an_niu_chang_an_kai_guan_tou_ying_yi

- alias: 书房按钮长按—开关投影仪
  initial_state: false
  trigger:
    - platform: event
      event_type: xiaomi_aqara.cube_action
      event_data:
        entity_id: binary_sensor.cube_158d0002a66db1
        action_type: shake_air
    # - platform: event
    #   event_type: xiaomi_aqara.click
    #   event_data:
    #     entity_id: binary_sensor.switch_158d000201a73f
    #     click_type: long_click_press
  action:
    - service: zhimsg.ke_ting_yin_xiang
      data_template:
        message: '正在{% if is_state("media_player.shu_fang_tou_ying_yi", "on") %}关闭{% else %}打开{% endif %}投影仪'
    - service: media_player.toggle
      entity_id: media_player.shu_fang_tou_ying_yi
    - service: automation.trigger
      data_template:
        entity_id: 'automation.shu_fang_tou_ying_yi_{% if is_state("media_player.shu_fang_tou_ying_yi", "off") %}guan_bi_shou_wei{% else %}kai_qi_zhun_bei{% endif %}_pei_tao'
    - service_template: 'switch.turn_{% if is_state("media_player.shu_fang_tou_ying_yi", "off") %}off{% else %}on{% endif %}'
      entity_id: switch.shu_fang_yin_xiang
