- alias: 睡眠准备
  trigger:
    - platform: time
      at: '20:30:00'
  action:
    - service: cover.close_cover
      entity_id: cover.shu_fang_chuang_lian
    # - service: fan.set_speed
    #   data:
    #     entity_id: fan.ci_wo_jing_hua_qi
    #     speed: Silent
    - service: climate.set_temperature
      data:
        entity_id: climate.zhu_wo_kong_diao
        temperature: 25
        hvac_mode: cool
    - service: climate.set_temperature
      data:
        entity_id: climate.er_tong_fang_kong_diao
        temperature: 25
        hvac_mode: cool
    - service: climate.set_fan_mode
      data:
        entity_id: climate.zhu_wo_kong_diao
        fan_mode: 五档
    - service: climate.set_fan_mode
      data:
        entity_id: climate.er_tong_fang_kong_diao
        fan_mode: 五档

- alias: 睡眠开始
  trigger:
    - platform: time
      at: '21:30:00'
  action:
    - service: xiaomi_miio.fan_set_led_brightness
      data:
        entity_id: fan.ke_ting_xin_feng_ji
        brightness: 2
    - service: xiaomi_miio.fan_set_led_brightness
      data:
        entity_id: fan.zhu_wo_xin_feng_ji
        brightness: 2
    - service: zhimsg.ke_ting_yin_xiang
      data:
        message: 音量30

- alias: 睡眠深入
  trigger:
    - platform: time
      at: '00:00:01'
  action:
    - service: shell_command.magic_off
    - service: climate.set_fan_mode
      data:
        entity_id: climate.zhu_wo_kong_diao
        fan_mode: 一档
    - service: climate.set_fan_mode
      data:
        entity_id: climate.er_tong_fang_kong_diao
        fan_mode: 一档
    - service: climate.set_temperature
      data:
        entity_id: climate.zhu_wo_kong_diao
        temperature: 26
    - service: climate.set_temperature
      data:
        entity_id: climate.er_tong_fang_kong_diao
        temperature: 27

- alias: 睡眠空调
  trigger:
    - platform: time
      at: '00:02:01'
  condition:
    - condition: numeric_state
      entity_id: sensor.yang_tai_wen_du
      below: 28
action:
    - service: climate.turn_off
      entity_id: climate.zhu_wo_kong_diao
    - service: climate.turn_off
      entity_id: climate.er_tong_fang_kong_diao
    - service: climate.turn_off
      entity_id: climate.shu_fang_kong_diao

- alias: 睡眠早起
  trigger:
    - platform: time
      at: '06:00:00'
  action:
    - service: shell_command.magic_on
    - service: xiaomi_miio.fan_set_led_brightness
      data:
        entity_id: fan.ke_ting_xin_feng_ji
        brightness: 0

- alias: 睡眠完成
  trigger:
    - platform: time
      at: '08:00:00'
  action:
    - service: xiaomi_miio.fan_set_led_brightness
      data:
        entity_id: fan.zhu_wo_xin_feng_ji
        brightness: 0
    - service: zhimsg.ke_ting_yin_xiang
      data:
        message: 音量30
    - service: climate.set_fan_mode
      data:
        entity_id: climate.zhu_wo_kong_diao
        fan_mode: 自动
    - service: climate.set_fan_mode
      data:
        entity_id: climate.er_tong_fang_kong_diao
        fan_mode: 自动
    # - service: fan.turn_off
    #   entity_id: fan.er_tong_fang_feng_shan
    - service: fan.turn_off
      entity_id: fan.shu_fang_feng_shan
    # - service: fan.turn_off
    #   entity_id: fan.zhu_wo_feng_shan
    - service: cover.open_cover
      entity_id: cover.shu_fang_chuang_lian
    - service: fan.set_speed
      data:
        entity_id: fan.zhu_wo_xin_feng_ji
        speed: Middle
    # - condition: time
    #   weekday:
    #     - mon
    #     - tue
    #     - wed
    #     - thu
    #     - fri
    # - service: automation.trigger
    #   entity_id: automation.shui_mian_yan_chang

# - alias: 睡眠延长
#   trigger:
#     - platform: time
#       at: '09:00:00'
#   condition:
#     - condition: time
#       weekday:
#         - sat
#         - sun
#   action:
