- alias: 餐厅筒灯同步调控
  trigger:
    - platform: state
      entity_id: switch.can_ting_tong_deng, light.can_ting_tong_deng
  action:
    - service_template: '{% if trigger.to_state.state == "on" %}homeassistant.turn_on{% else %}light.turn_off{% endif %}'
      data_template:
        entity_id: '{% if trigger.entity_id == "switch.can_ting_tong_deng" %}light.can_ting_tong_deng{% else %}switch.can_ting_tong_deng{% endif %}'

- alias: 客厅筒灯同步调控
  trigger:
    - platform: state
      entity_id: switch.ke_ting_tong_deng, light.ke_ting_tong_deng
  action:
    - service_template: '{% if trigger.to_state.state == "on" %}homeassistant.turn_on{% else %}light.turn_off{% endif %}'
      data_template:
        entity_id: '{% if trigger.entity_id == "switch.ke_ting_tong_deng" %}light.ke_ting_tong_deng{% else %}switch.ke_ting_tong_deng{% endif %}'
