- alias: 洗手间感应-开灯
  trigger:
    - platform: state
      entity_id: binary_sensor.motion_sensor_158d0001f4a238
      to: 'on'
  condition:
    # - condition: state
    #   entity_id: light.xi_shou_jian_deng
    #   state: 'off'
    - condition: time
      after: '18:00'
      before: '22:00'
  action:
    - service: light.turn_on
      entity_id: light.xi_shou_jian_deng
    - service: automation.turn_off
      entity_id: automation.xi_shou_jian_gan_ying_yan_shi_guan_deng
    - service: automation.turn_on
      entity_id: automation.xi_shou_jian_gan_ying_yan_shi_guan_deng

- alias: 洗手间感应延时-关灯
  initial_state: false
  mode: restart
  trigger:
    - platform: time_pattern
      minutes: '/3'
  condition:
    - condition: state
      entity_id: binary_sensor.motion_sensor_158d0001f4a238
      state: 'off'
    - condition: state
      entity_id: binary_sensor.door_window_sensor_158d0003cf4735
      state: 'on'
  action:
    - service: light.turn_off
      entity_id: light.xi_shou_jian_deng
    - service: automation.turn_off
      entity_id: automation.xi_shou_jian_gan_ying_yan_shi_guan_deng
